version: '3'

name: mevn

services:
  database:
    image: 'mongo'
    container_name: 'mevn-mongo-container'
    environment:
      - MONGO_INITDB_DATABASE=mevn-db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./db/mongo-volume:/data/db
    ports:
      - '27018:27017'
    networks:
      - mevn-network

networks:
  mevn-network:
    driver: bridge
